name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive
      - name: build all
        run: |
          pushd demo
          ./ng all
          popd
      - name: test simple debug
        run: demo/_out/linux/demo_simple_debug
      - name: test simple release
        run: demo/_out/linux/demo_simple_release
      - name: test simple nomicroprofile
        run: demo/_out/linux/demo_simple_nomicroprofile
      - name: test simple lto
        run: demo/_out/linux/demo_simple_lto
      - name: test simple asan
        run: demo/_out/linux/demo_simple_asan
      - name: test simple ubsan
        run: demo/_out/linux/demo_simple_ubsan
      - name: test simple tsan
        run: demo/_out/linux/demo_simple_tsan
      - name: test simple msan
        run: demo/_out/linux/demo_simple_msan

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive
      - name: build all
        run: |
          pushd demo
          ./ng all
          popd
      - name: test simple debug
        run: demo/_out/osx/demo_simple_debug
      - name: test simple release
        run: demo/_out/osx/demo_simple_release
      - name: test simple nomicroprofile
        run: demo/_out/osx/demo_simple_nomicroprofile
      - name: test simple lto
        run: demo/_out/osx/demo_simple_lto
      - name: test simple asan
        run: demo/_out/osx/demo_simple_asan
      - name: test simple ubsan
        run: demo/_out/osx/demo_simple_ubsan
      - name: test simple tsan
        run: demo/_out/osx/demo_simple_tsan


  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive
      - name: build all
        run: |
          pushd demo
          ./ng all
          popd
      - name: test simple debug
        run: demo/_out/win32/demo_simple_debug
      - name: test simple release
        run: demo/_out/win32/demo_simple_release
      - name: test simple nomicroprofile
        run: demo/_out/win32/demo_simple_nomicroprofile
